version: '3'
services:
  cassandradb:
    image: cassandra
    container_name: cassandradb
    ports:
      - 9042:9042

  app:
    container_name: mailer-app
    ports:
      - 8080:8080
    build:
      context: .
    restart: always

